image: Ubuntu2204 # образ для сборки
stack: node 20 # окружение
branches:
  only:
    - main # ветка git
cache: node_modules # кеширование
install:
  - npm install --force # команда установки зависимостей
build: off
test_script:
  - npm run lint && npm test # скрипт сборки